---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[poise-runit::default]
    attributes:
  - name: apache
    run_list:
      - recipe[poise-runit::nginx_test]
    attributes:
  - name: nginx
    run_list:
      - recipe[poise-runit::apache_test]
    attributes:
