name 'poise-runit'
maintainer 'Luis De Siqueira'
maintainer_email 'LouTheBrew@gmail.com'
license 'MIT'
description 'Installs/Configures runit'
long_description 'Installs/Configures runit'
version '0.0.11'

depends 'build-essential'
depends 'poise'
depends 'poise-ruby-init'
